global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using ReLogic.Content;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Terraria;
global using Terraria.GameContent;
global using Terraria.Localization;
global using Terraria.ModLoader;
global using static Microsoft.Xna.Framework.MathHelper;